import './globals.css';
import Navbar from '@/components/navigations/navbar/Navbar';
import Footer from '@/components/footer/Footer';

export const metadata = {
	title: {
		default: 'NextJS 14 blog',
		template: '%s | NextJS 14',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<div className='container'>
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
